apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbreplica2
spec:
  selector:
   matchLabels:
    app: app-dbreplica2
  replicas: 1
  template:
    metadata:
      labels:
        app: app-dbreplica2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - dbreplica2
      containers:
        - name: dbreplica2
          image: rust-postgres-dbreplica2:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: postgres-username
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-secret
                 key: postgres-password
           - name: POSTGRES_DB
             valueFrom:
               configMapKeyRef:
                 name: postgres-configmap
                 key: postgres-dbname
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: dbreplica2-storage
      volumes:
        - name: dbreplica2-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim-dbreplica2
---
    kind: PersistentVolume
    apiVersion: v1
    metadata:
      name: postgres-pv-volume-dbreplica2
      labels:
        type: local
    spec:
      storageClassName: manual
      claimRef:
        name: postgres-pv-claim-dbreplica2
        namespace: default
      capacity:
        storage: 2Gi
      accessModes:
        - ReadWriteMany
      hostPath:
        path: "/mnt/data/dbreplica2"
---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: postgres-pv-claim-dbreplica2
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
---
    apiVersion: v1
    kind: Service
    metadata:
      name: dbreplica2
    spec:
      ports:
        - port: 5432
          targetPort: 5432
      selector:
        app: app-dbreplica2
